---

- name: Setup Java
  hosts: allnodes
  roles:
    - oracleJava

- name: Installing PreRequisites
  hosts: allnodes
  roles: 
    - PreRequisite

- name: Downloading Ambari Repo
  hosts: allnodes
  roles:
    - AmbariRepo

- name: Setup Ambari Server
  hosts: ambariserver
  roles:
    - AmbariServer

- name: Setup Ambari Agent
  hosts: allnodes
  roles:
    - AmbariAgent

- name: Install MySQL
  hosts: mysql
  roles:
    - MySQL

- name: SetUp KDC
  hosts: kdcmaster
  roles:
    - kerberos_server

- name: Set Kerberos agents
  hosts: all
  roles:
    - kerberos_agent 

- name: Apply Blueprint
  hosts: ambariserver
  roles: 
    - blueprint
